/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuestsIndexRouteImport } from './routes/guests/index'
import { Route as GuestsNewRouteImport } from './routes/guests/new'
import { Route as GuestsIdRouteImport } from './routes/guests/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestsIndexRoute = GuestsIndexRouteImport.update({
  id: '/guests/',
  path: '/guests/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestsNewRoute = GuestsNewRouteImport.update({
  id: '/guests/new',
  path: '/guests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestsIdRoute = GuestsIdRouteImport.update({
  id: '/guests/$id',
  path: '/guests/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guests/$id': typeof GuestsIdRoute
  '/guests/new': typeof GuestsNewRoute
  '/guests': typeof GuestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guests/$id': typeof GuestsIdRoute
  '/guests/new': typeof GuestsNewRoute
  '/guests': typeof GuestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guests/$id': typeof GuestsIdRoute
  '/guests/new': typeof GuestsNewRoute
  '/guests/': typeof GuestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/guests/$id' | '/guests/new' | '/guests'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/guests/$id' | '/guests/new' | '/guests'
  id: '__root__' | '/' | '/guests/$id' | '/guests/new' | '/guests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuestsIdRoute: typeof GuestsIdRoute
  GuestsNewRoute: typeof GuestsNewRoute
  GuestsIndexRoute: typeof GuestsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guests/': {
      id: '/guests/'
      path: '/guests'
      fullPath: '/guests'
      preLoaderRoute: typeof GuestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guests/new': {
      id: '/guests/new'
      path: '/guests/new'
      fullPath: '/guests/new'
      preLoaderRoute: typeof GuestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guests/$id': {
      id: '/guests/$id'
      path: '/guests/$id'
      fullPath: '/guests/$id'
      preLoaderRoute: typeof GuestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuestsIdRoute: GuestsIdRoute,
  GuestsNewRoute: GuestsNewRoute,
  GuestsIndexRoute: GuestsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
